#release configuration
#Sun Mar 16 12:39:21 CET 2025
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.local.jarios\:import-from-gc=1.0.1-SNAPSHOT
project.rel.local.jarios\:import-from-gc=1.0.0
project.scm.local.jarios\:import-from-gc.connection=scm\:git\:git\://github.com/contratacionmalaga/ImportFromGc.git
project.scm.local.jarios\:import-from-gc.developerConnection=scm\:git\:ssh\://github.com/contratacionmalaga/ImportFromGc.git
project.scm.local.jarios\:import-from-gc.tag=v1.2.2
project.scm.local.jarios\:import-from-gc.url=https\://github.com/contratacionmalaga/ImportFromGc
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v1.0.0
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:ssh\://github.com/contratacionmalaga/ImportFromGc.git
