#release configuration
#Sat Jun 14 15:58:14 CEST 2025
completedPhase=generate-release-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.local.jarios\:import-from-gc=1.0.2-SNAPSHOT
project.rel.local.jarios\:import-from-gc=1.0.1
project.scm.local.jarios\:import-from-gc.connection=scm\:git\:https\://github.com/contratacionmalaga/import-from-gc.git
project.scm.local.jarios\:import-from-gc.developerConnection=scm\:git\:git@github.com\:contratacionmalaga/import-from-gc.git
project.scm.local.jarios\:import-from-gc.tag=HEAD
project.scm.local.jarios\:import-from-gc.url=https\://github.com/contratacionmalaga/import-from-gc
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[RELEASE]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v1.0.1
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:contratacionmalaga/import-from-gc.git
