# # # # # # # # # # # # # # # # # # # # #
#                                       #
#       CONFIGURACIÓN DE HIBERNATE      #
#                                       #
# # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CONFIGURACIÓN DEL BATCH PARA LA MEJORA DEL RENDIMIENTO
#
# Mejora drásticamente el rendimiento en operaciones masivas al reducir viajes al servidor de BD.
hibernate.jdbc.batch_size=50
# Permite que Hibernate agrupe más eficientemente por tipo de entidad (por ejemplo, si estás insertando muchos Entry y Log, los agrupa por clase).
hibernate.order_inserts=true
# Igual que order_inserts, pero con las sentencias UPDATE.
hibernate.order_updates=true
# Permite que Hibernate haga batching incluso cuando usas versionamiento optimista (@Version en entidades).
hibernate.jdbc.batch_versioned_data=true

# # # # # # # # # # # # # # # # # # # # # #
# DESACTIVO EL SEGUNDO NIVEL DE CACHE
#
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false

# # # # # # # # # # # # # # # # # # # # # # # # # # #
# ACTIVACIÓN DE ESTADÍSTICAS -- SOLO DESARROLLO
#
hibernate.generate_statistics=true

# # # # # # # # # # # # # # # # # # # #
# CONFIGURACIÓN DEL POOL HIKARICP
#
hibernate.hikari=jarios
hibernate.hikari.maximumPoolSize=30
hibernate.hikari.minimumIdle=15
# 30 minutos
hibernate.hikari.maxLifetime=1800000
# 15 segundos
hibernate.hikari.leakDetectionThreshold=15000
# 30 segundos
hibernate.hikari.idleTimeout=30000
# 30 segundos
hibernate.hikari.connectionTimeout=30000
# 5 segundos
hibernate.hikari.validationTimeout=5000
# 1 segundo
hibernate.hikari.initializationFailTimeout=1000
# 5 minutos
hibernate.hikari.keepaliveTime=300000
# hibernate.hikari.connectionInitSql=SELECT 1 --- EN ORACLE PRODUCE ERROR
hibernate.hikari.poolName=import_from_gc_hikari_pool
hibernate.hikari.readOnly=false
hibernate.hikari.isolateInternalQueries=true

# # # # # # # # # # # # # # # # # # # # #
# ESQUEMA. Opciones:
#
#       validate: validate the schema, makes no changes to the database.
#       update: update the schema si detecta cambios.
#       create: creates the schema, destroying previous data.
#       create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
#       none: does nothing with the schema, makes no changes to the database-->
hibernate.hbm2ddl.auto=none

# # # # # # # # # # # # # # # # # # # # #
# LOGS
#
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.highlight_sql=false
